name: MotorElevator
version: '1.0.0'
main: me.motor.motorelevator.MotorElevator
commands:
  motorelevator:
    aliases:
      - 엘베
      - elevator
    description: Reloads the MotorElevator configuration
    usage: /<command> reload
    permission: motor.elevator.reload

permissions:
  motor.elevator.reload:
    description: Allows the player to reload the MotorElevator Messages
    default: op